[package]
name = "SAT_solver"
version = "0.1.0"
authors = ["yusuke kataoka <yusuke.kataoka09@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
